[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Set Via_ir to either true or false!
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
